---

- name: Remove ntp and ntpstat
  apt:
    name: ['ntp', 'ntpstat']
    state: absent
    autoremove: true
    purge: true
  tags: timedatectl

- name: Setup timesync config
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: run timedatectl
  when: ansible_service_mgr == "systemd"
  tags: timedatectl

- name: Enable and run systemd-timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: true
  tags: timedatectl

- name: Set timezone
  timezone: name={{ configure_timesyncd_timezone }}
  when: ansible_service_mgr == "systemd"
  notify: restart timesyncd
  tags: timedatectl
